import React,{useState}from'react';
import{submitReservation}from'../controllers/ReservationController';
import{saveReservationDemo}from'../services/reservationService';
export default function ReservationView(){
 const[form,setForm]=useState({name:'',email:'',phone:'',date:'',time:'',guests:'2',notes:''}),[sent,setSent]=useState(false);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const submit=async e=>{e.preventDefault();await saveReservationDemo(submitReservation(form));setSent(true)};
 return <section className="content-wrap page-section reservation-page">
  <div className="reservation-intro"><span className="eyebrow">A SEAT AT OUR TABLE</span><h1 className="page-title">Make it a <em>moment.</em></h1><p className="page-lead">A slow lunch, a little celebration, or simply a reason to get together. We’ll save you a place.</p><div className="reservation-perks"><span>✦ Thoughtful hospitality</span><span>✦ Freshly prepared favourites</span><span>✦ Made for good company</span></div><div className="reservation-note"><b>Planning something special?</b><p>Share your occasion or seating preference in the notes. Our team can follow up once a real booking service is connected.</p></div></div>
  <form className="reservation-form" onSubmit={submit}><div className="form-heading"><span className="eyebrow">YOUR VISIT</span><h2>Reserve a table</h2><p>Tell us a little about your plans.</p></div>{sent&&<div className="success-note">Thank you, {form.name}! Your demo reservation request is saved locally. Connect a backend to receive real bookings.</div>}<div className="form-grid"><label>Your name<input required name="name" value={form.name} onChange={change} placeholder="Your name"/></label><label>Email address<input required type="email" name="email" value={form.email} onChange={change} placeholder="you@example.com"/></label><label>Phone number<input required name="phone" value={form.phone} onChange={change} placeholder="Phone number"/></label><label>Guests<select name="guests" value={form.guests} onChange={change}>{[1,2,3,4,5,6,7,8,9,10].map(n=><option key={n}>{n}</option>)}</select></label><label>Date<input required type="date" min={new Date().toISOString().slice(0,10)} name="date" value={form.date} onChange={change}/></label><label>Preferred time<input required type="time" name="time" value={form.time} onChange={change}/></label></div><label>Anything we should know?<textarea name="notes" value={form.notes} onChange={change} placeholder="Birthday, anniversary, seating preference..."/></label><button className="primary-btn" type="submit">Request a table <span>↗</span></button><small className="form-disclaimer">Demo form · No real reservation is created yet.</small></form>
 </section>
}
